import {supabase,shell,setApp,money,fmtDate,esc,toast} from "./app.js";
const p=await shell("Dashboard");if(!p)throw 0;
async function load(){const [a,b,c,f,t]=await Promise.all([
supabase.from("inventory_items").select("*",{count:"exact",head:true}).neq("status","archived"),
supabase.from("borrow_requests").select("*",{count:"exact",head:true}).eq("status","pending"),
supabase.from("borrowings").select("*",{count:"exact",head:true}).eq("status","active"),
supabase.from("cash_funds").select("id,name,balance,status").order("name"),
supabase.from("finance_transactions").select("id,type,amount,description,transaction_date,cash_funds(name)").order("transaction_date",{ascending:false}).limit(8)]);
[a,b,c,f,t].forEach(x=>{if(x.error)throw x.error});const funds=f.data||[],tx=t.data||[];const total=funds.reduce((s,x)=>s+Number(x.balance||0),0),income=tx.filter(x=>x.type==="income").reduce((s,x)=>s+Number(x.amount),0),expense=tx.filter(x=>x.type==="expense").reduce((s,x)=>s+Number(x.amount),0);
setApp(`<div class="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p class="text-sm font-bold text-orange-600">FEBIAS College of Bible · OSI</p><h1 class="text-3xl font-black">Good day, ${esc((p.full_name||"User").split(" ")[0])}.</h1><p class="mt-1 text-sm text-slate-500">Operational snapshot for inventory and finances.</p></div><a class="btn btn-primary" href="inventory.html">+ Add inventory</a></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div class="kpi"><div class="label">Inventory Items</div><div class="value">${a.count||0}</div><div class="text-xs text-slate-500">Active records</div></div><div class="kpi"><div class="label">Pending Requests</div><div class="value">${b.count||0}</div><div class="text-xs text-slate-500">Need review</div></div><div class="kpi"><div class="label">Currently Borrowed</div><div class="value">${c.count||0}</div><div class="text-xs text-slate-500">Open borrowings</div></div><div class="kpi"><div class="label">Cash Funds</div><div class="value">${money(total)}</div><div class="text-xs text-slate-500">${funds.length} funds</div></div><div class="kpi"><div class="label">Recent Net</div><div class="value">${money(income-expense)}</div><div class="text-xs text-slate-500">Latest ledger records</div></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-3"><section class="card lg:col-span-2"><div class="flex items-center justify-between border-b p-5"><div><h2 class="font-black">Recent financial activity</h2><p class="text-xs text-slate-500">Latest income and expense records</p></div><a href="finance.html" class="text-sm font-bold text-orange-600">Open finance →</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Fund</th><th>Amount</th></tr></thead><tbody>${tx.map(x=>`<tr><td>${fmtDate(x.transaction_date)}</td><td><span class="badge ${x.type==="income"?"badge-green":"badge-red"}">${esc(x.type)}</span></td><td>${esc(x.description)}</td><td>${esc(x.cash_funds?.name||"—")}</td><td class="font-bold">${money(x.amount)}</td></tr>`).join("")||`<tr><td colspan="5" class="text-center text-slate-500 py-8">No finance records yet.</td></tr>`}</tbody></table></div></section><section class="card"><div class="border-b p-5"><h2 class="font-black">Cash funds</h2><p class="text-xs text-slate-500">Current balances</p></div><div class="p-4 space-y-3">${funds.map(x=>`<div class="rounded-xl border p-3"><div class="flex justify-between gap-2"><span class="font-bold">${esc(x.name)}</span><span class="font-black">${money(x.balance)}</span></div><div class="mt-1 text-xs text-slate-500">${esc(x.status)}</div></div>`).join("")||`<p class="p-4 text-sm text-slate-500">Create a fund in Finance.</p>`}</div></section></div>`)}
load().catch(e=>toast(e.message,false));